# Generated by Django 6.0 on 2026-04-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('physics', 'Физика'), ('algebra', 'Алгебра'), ('geometry', 'Геометрия')], max_length=20)),
                ('text', models.CharField(max_length=200, verbose_name='Формула')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
