# Generated by Django 6.0 on 2026-01-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tests_completed',
            field=models.IntegerField(default=0),
        ),
    ]
