# Generated by Django 5.2 on 2025-04-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_favoriteformula'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=100)),
                ('correct_answer', models.CharField(max_length=100)),
                ('options', models.JSONField(default=list)),
            ],
        ),
    ]
